module.exports = {
  url: "https://bluecoreshield.com",
  buildDate: new Date().toISOString().slice(0, 10),
  blogPageSize: 15,
  staticPaths: [
    "/index.html",
    "/about.html",
    "/contact.html",
    "/services.html",
    "/industries.html",
    "/areas.html",
    "/services/armed-security.html",
    "/services/unarmed-security.html",
    "/services/mobile-patrol.html",
    "/services/fire-watch.html",
    "/services/construction-security.html",
    "/services/event-security.html",
    "/industries/retail.html",
    "/industries/corporate.html",
    "/industries/warehouse.html",
    "/industries/construction.html",
    "/industries/residential.html",
    "/industries/healthcare.html",
    "/industries/hospitality.html",
    "/industries/education.html",
    "/industries/events.html",
    "/areas/manhattan.html",
    "/areas/brooklyn.html",
    "/areas/queens.html",
    "/areas/bronx.html",
    "/areas/staten-island.html",
    "/areas/long-island.html",
    "/areas/westchester.html",
    "/areas/new-jersey.html",
  ],
};
